service: LangChainBook-ChatGPTSlackFunction
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: '*'
          
	
custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: false


package:
  patterns:
    - '!.env'
    - '!.gitignore'
    - '!.python-version'
    - '!.git/**'
    - '!node_modules/**'
    - '!package.json'
    - '!package-lock.json'

functions:
  app:
    name: LangChainBook-ChatGPTSlackFunction-${sls:stage}-app
    handler: app.handler
    runtime: python3.10
    memorySize: 512
    timeout: 900
    url: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin